version: '2'
services:
  web:
    build: .
    ports:
      - "5500:5500"
    depends_on:
      - db
  db:
    restart: always
    image: "postgres"
    volumes:
      - db:/var/lib/postgresql/data
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    env_file:
      - "./database.env"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432", "-d", "warehouse_inventory", "-U", "postgres"]
      interval: 10s

volumes:
  db: { }
